-- 002_tableaux_et_grands_ours
-- Produits ajoutés au dépôt après l'installation initiale.
--
-- catalogue-initial.json n'est semé qu'une fois, sur une table vide
-- (Setup::seedCatalog). Cette migration est donc le seul moyen de faire
-- remonter de nouveaux produits dans la base de production.
--
-- Rejouable sans risque : ON DUPLICATE KEY UPDATE sur le slug unique.
-- Le prix, la disponibilité, la mise en avant et le rang restent la
-- propriété de l'administration une fois le produit créé.

INSERT INTO products
  (slug, name, category, description, price_gnf, price_mode, price_label, price_prefix, tag, image_url, image_srcset, image_sizes, image_alt, image_width, image_height, image_position, visual_variant, care_json, status, availability, featured_home, sort_order)
VALUES
  ('tableau-pivoines-roses', 'Tableau pivoines roses', 'tableaux', 'Pivoines roses et blanches peintes sur un fond vert tendre, rehaussées de fils dorés. Le motif floral de la sélection, à accrocher au-dessus d’un buffet ou d’un lit.', 250000, 'fixed', NULL, NULL, 'Décoration murale', '/optimized/produit-tableau-pivoines-roses-810.webp', '/optimized/produit-tableau-pivoines-roses-480.webp 480w, /optimized/produit-tableau-pivoines-roses-810.webp 810w', '(max-width: 720px) calc(100vw - 40px), (max-width: 900px) 50vw, 25vw', 'Tableau peint de pivoines roses et blanches sur fond vert doux', 810, 1080, NULL, NULL, NULL, 'active', 'available', 0, 840),
  ('tableau-feuilles-monstera', 'Tableau feuilles de monstera', 'tableaux', 'Aquarelle de feuilles de monstera vertes sur fond blanc, dans un cadre noir. Un végétal graphique et discret pour un salon ou un bureau.', 350000, 'fixed', NULL, NULL, 'Décoration murale', '/optimized/produit-tableau-feuilles-monstera-810.webp', '/optimized/produit-tableau-feuilles-monstera-480.webp 480w, /optimized/produit-tableau-feuilles-monstera-810.webp 810w', '(max-width: 720px) calc(100vw - 40px), (max-width: 900px) 50vw, 25vw', 'Tableau aquarelle de feuilles de monstera vertes sur fond blanc, cadre noir', 810, 1080, NULL, NULL, NULL, 'active', 'available', 0, 850),
  ('tableau-femme-fleurs-blanches', 'Tableau femme aux fleurs blanches', 'tableaux', 'Portrait en noir et blanc d’une femme coiffée de larges fleurs blanches, rehaussé de feuillages dorés.', 350000, 'fixed', NULL, NULL, 'Décoration murale', '/optimized/produit-tableau-femme-fleurs-blanches-810.webp', '/optimized/produit-tableau-femme-fleurs-blanches-480.webp 480w, /optimized/produit-tableau-femme-fleurs-blanches-810.webp 810w', '(max-width: 720px) calc(100vw - 40px), (max-width: 900px) 50vw, 25vw', 'Tableau d’une femme coiffée de fleurs blanches, feuillages dorés', 810, 1080, NULL, NULL, NULL, 'active', 'available', 0, 860),
  ('tableau-horloge-femme-rouge', 'Tableau-horloge femme en rouge', 'tableaux', 'Tableau décoratif à cadran intégré, cerclé d’un liseré doré : une horloge murale qui se regarde d’abord comme un tableau.', 350000, 'fixed', NULL, NULL, 'Tableau-horloge', '/optimized/produit-tableau-horloge-femme-rouge-810.webp', '/optimized/produit-tableau-horloge-femme-rouge-480.webp 480w, /optimized/produit-tableau-horloge-femme-rouge-810.webp 810w', '(max-width: 720px) calc(100vw - 40px), (max-width: 900px) 50vw, 25vw', 'Tableau-horloge doré représentant une femme au chapeau rouge', 810, 1080, NULL, NULL, NULL, 'active', 'available', 0, 870),
  ('tableau-cheval-gris', 'Tableau cheval gris', 'tableaux', 'Portrait d’un cheval gris à la crinière tressée, harnais noir et doré. Un sujet sobre et racé, qui tient aussi bien dans un salon que dans un bureau.', 350000, 'fixed', NULL, NULL, 'Décoration murale', '/optimized/produit-tableau-cheval-gris-810.webp', '/optimized/produit-tableau-cheval-gris-480.webp 480w, /optimized/produit-tableau-cheval-gris-810.webp 810w', '(max-width: 720px) calc(100vw - 40px), (max-width: 900px) 50vw, 25vw', 'Tableau d’un cheval gris à la crinière tressée, harnais noir et or', 810, 1080, NULL, NULL, NULL, 'active', 'available', 0, 880),
  ('tableau-cerf-dore', 'Tableau cerf doré', 'tableaux', 'Cerf doré sur un fond noir et or, rehaussé de cristaux, dans un cadre doré. Une pièce lumineuse pour un mur d’entrée ou de salon.', 450000, 'fixed', NULL, NULL, 'Décoration murale', '/optimized/produit-tableau-cerf-dore-810.webp', '/optimized/produit-tableau-cerf-dore-480.webp 480w, /optimized/produit-tableau-cerf-dore-810.webp 810w', '(max-width: 720px) calc(100vw - 40px), (max-width: 900px) 50vw, 25vw', 'Tableau cerf doré sur fond noir et or rehaussé de cristaux, cadre doré', 810, 1080, NULL, NULL, NULL, 'active', 'available', 0, 890),
  ('tableau-femme-robe-orange', 'Tableau femme à la robe orange', 'tableaux', 'Silhouette en robe orange et large chapeau, soulignée d’un néon doré et de cristaux, sur un fond vert profond.', 450000, 'fixed', NULL, NULL, 'Décoration murale', '/optimized/produit-tableau-femme-robe-orange-810.webp', '/optimized/produit-tableau-femme-robe-orange-480.webp 480w, /optimized/produit-tableau-femme-robe-orange-810.webp 810w', '(max-width: 720px) calc(100vw - 40px), (max-width: 900px) 50vw, 25vw', 'Tableau d’une femme en robe orange à large chapeau, néon doré', 810, 1080, NULL, NULL, NULL, 'active', 'available', 0, 900),
  ('tableau-elephant-bleu-or', 'Tableau éléphant bleu et or', 'tableaux', 'Éléphant bleu et or entièrement incrusté de cristaux, dans un cadre argenté. La pièce la plus imposante de la sélection.', 800000, 'fixed', NULL, NULL, 'Grand format', '/optimized/produit-tableau-elephant-bleu-or-810.webp', '/optimized/produit-tableau-elephant-bleu-or-480.webp 480w, /optimized/produit-tableau-elephant-bleu-or-810.webp 810w', '(max-width: 720px) calc(100vw - 40px), (max-width: 900px) 50vw, 25vw', 'Tableau éléphant bleu et or incrusté de cristaux, cadre argenté', 810, 1080, NULL, NULL, NULL, 'active', 'available', 0, 910),
  ('grand-ours-beige', 'Grand ours beige', 'peluches', 'Grand ours en peluche beige au museau clair, noué d’un nœud vichy. Un cadeau qui se remarque, seul ou à côté d’un bouquet.', 600000, 'fixed', NULL, NULL, 'Grand format', '/optimized/produit-grand-ours-beige-810.webp', '/optimized/produit-grand-ours-beige-480.webp 480w, /optimized/produit-grand-ours-beige-810.webp 810w', '(max-width: 720px) calc(100vw - 40px), (max-width: 900px) 50vw, 25vw', 'Grand ours en peluche beige au nœud vichy', 810, 1080, NULL, NULL, NULL, 'active', 'available', 0, 780),
  ('grand-ours-blanc', 'Grand ours blanc', 'peluches', 'Grand ours en peluche blanc au pelage bouclé, noué d’un nœud vichy. Doux et volumineux, pour une naissance ou une grande occasion.', 600000, 'fixed', NULL, NULL, 'Grand format', '/optimized/produit-grand-ours-blanc-810.webp', '/optimized/produit-grand-ours-blanc-480.webp 480w, /optimized/produit-grand-ours-blanc-810.webp 810w', '(max-width: 720px) calc(100vw - 40px), (max-width: 900px) 50vw, 25vw', 'Grand ours en peluche blanc au nœud vichy', 810, 1080, NULL, NULL, NULL, 'active', 'available', 0, 790),
  ('grand-ours-rose', 'Grand ours rose « Love »', 'peluches', 'Grand ours en peluche rose pâle, cœur brodé « Love » sur la poitrine. Le compagnon des déclarations et des anniversaires.', 600000, 'fixed', NULL, NULL, 'Grand format', '/optimized/produit-grand-ours-rose-810.webp', '/optimized/produit-grand-ours-rose-480.webp 480w, /optimized/produit-grand-ours-rose-810.webp 810w', '(max-width: 720px) calc(100vw - 40px), (max-width: 900px) 50vw, 25vw', 'Grand ours en peluche rose au cœur brodé « Love »', 810, 1080, NULL, NULL, NULL, 'active', 'available', 0, 800),
  ('grand-ours-marron', 'Grand ours marron', 'peluches', 'Grand ours en peluche marron au museau crème, noué d’un nœud vichy. L’ours classique, en très grand format.', 600000, 'fixed', NULL, NULL, 'Grand format', '/optimized/produit-grand-ours-marron-810.webp', '/optimized/produit-grand-ours-marron-480.webp 480w, /optimized/produit-grand-ours-marron-810.webp 810w', '(max-width: 720px) calc(100vw - 40px), (max-width: 900px) 50vw, 25vw', 'Grand ours en peluche marron au nœud vichy', 810, 1080, NULL, NULL, NULL, 'active', 'available', 0, 810),
  ('grand-ours-violet', 'Grand ours violet', 'peluches', 'Grand ours en peluche violet au museau blanc, noué d’un nœud vichy. Une couleur franche pour un cadeau qui sort de l’ordinaire.', 600000, 'fixed', NULL, NULL, 'Grand format', '/optimized/produit-grand-ours-violet-810.webp', '/optimized/produit-grand-ours-violet-480.webp 480w, /optimized/produit-grand-ours-violet-810.webp 810w', '(max-width: 720px) calc(100vw - 40px), (max-width: 900px) 50vw, 25vw', 'Grand ours en peluche violet au nœud vichy', 810, 1080, NULL, NULL, NULL, 'active', 'available', 0, 820)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  category = VALUES(category),
  description = VALUES(description),
  tag = VALUES(tag),
  image_url = VALUES(image_url),
  image_srcset = VALUES(image_srcset),
  image_sizes = VALUES(image_sizes),
  image_alt = VALUES(image_alt),
  image_width = VALUES(image_width),
  image_height = VALUES(image_height),
  image_position = VALUES(image_position),
  visual_variant = VALUES(visual_variant),
  care_json = VALUES(care_json),
  updated_at = CURRENT_TIMESTAMP;
