// Coordonnées officielles de la boutique — un seul endroit à modifier.
export const CONTACT = {
  tagline: 'Des fleurs pour chaque émotion',
  heroTitle: "L'amour se dit en fleur et chaque fleur a une histoire ...",
  // Forme d'usage, celle de l'enseigne « by Irma » : boutons, messages,
  // métadonnées. Le nom complet ne sert qu'à la présentation de la fondatrice.
  founder: 'Irma',
  founderFullName: 'Sandouno Irene Mayer',
  phone: '+224 610 81 17 17',
  phoneDisplay: '610 81 17 17',
  whatsapp: '224664327554',
  whatsappDisplay: '664 32 75 54',
  email: 'lizzirenedeco@gmail.com',
  instagram: '@lizzirenedeco',
  instagramUrl: 'https://instagram.com/lizzirenedeco',
  city: 'Conakry, Guinée',
  address: 'Kipé, Conakry — Guinée II',
  addressDetail:
    "À 50 m de l'école française, rue non bitumée, en face du collège Koffi Annan",
  hours: ['Lun – Sam : 8h30 – 21h30', 'Dim : 10h – 18h'],
}

// Variantes optimisées générées dans /public/optimized depuis /image-sources.
// `BASE_URL` préfixe le chemin quand le site est servi depuis un
// sous-dossier (GitHub Pages) — ne jamais écrire les chemins en dur.
const asset = (fichier) => `${import.meta.env.BASE_URL}${fichier}`

const responsivePhoto = ({
  nom,
  largeurs,
  alt,
  width,
  height,
  sizes = '(max-width: 720px) calc(100vw - 40px), (max-width: 900px) 50vw, 25vw',
}) => ({
  src: asset(`optimized/${nom}-${largeurs.at(-1)}.webp`),
  srcSet: largeurs
    .map((largeur) => `${asset(`optimized/${nom}-${largeur}.webp`)} ${largeur}w`)
    .join(', '),
  sizes,
  alt,
  width,
  height,
})

export const PHOTOS = {
  logo: {
    src: asset('optimized/logo-160.webp'),
    alt: 'Logo Lizzirene Déco',
    width: 160,
    height: 160,
  },
  vedette: responsivePhoto({
    nom: 'photo-vedette',
    largeurs: [480, 960],
    alt: 'Composition florale Lizzirene Déco dans un pot noir avec ruban jaune',
    width: 960,
    height: 1280,
  }),
  fondatrice: responsivePhoto({
    nom: 'la-fondatrice',
    largeurs: [480, 810],
    alt: 'Sandouno Irene Mayer, fondatrice de Lizzirene Déco',
    width: 810,
    height: 1080,
  }),
  fondatriceBoutique: responsivePhoto({
    nom: 'fondatrice-boutique',
    largeurs: [480, 810],
    alt: 'Fondatrice de Lizzirene Déco entourée de fleurs en boutique',
    width: 810,
    height: 1080,
  }),
  comiteMissGuinee: responsivePhoto({
    nom: 'comite-miss-guinee',
    largeurs: [640, 1080],
    alt: 'Les lauréates de Miss Guinée 2025 avec leurs bouquets Lizzirene Déco',
    width: 1080,
    height: 864,
    sizes: '(max-width: 900px) calc(100vw - 40px), 620px',
  }),
  clienteComblee: responsivePhoto({
    nom: 'cliente-comblee',
    largeurs: [480, 960],
    alt: "Cliente émue à la réception d'un bouquet de roses et d'un coffret cadeau Lizzirene Déco",
    width: 960,
    height: 1280,
    sizes: '(max-width: 900px) calc(100vw - 40px), 480px',
  }),
  bouquet: responsivePhoto({
    nom: 'bouquet-fleurs',
    largeurs: [480, 720],
    alt: 'Bouquet de roses rouges, gerbera blanc et gypsophile',
    width: 720,
    height: 1280,
  }),
  paquetEmballe: responsivePhoto({
    nom: 'paquet-emballe',
    largeurs: [480, 810],
    alt: 'Coffret cadeau en forme de cœur noué avec un ruban rouge',
    width: 810,
    height: 1080,
  }),
  fleursFraiches: responsivePhoto({
    nom: 'fleurs-fraiches',
    largeurs: [640, 1200],
    alt: 'Roses fraîches orange et roses couvertes de gouttes d’eau',
    width: 1200,
    height: 900,
  }),
  decoFlorale: responsivePhoto({
    nom: 'deco-floral',
    largeurs: [640, 1200],
    alt: 'Composition florale colorée dans un panier en osier',
    width: 1200,
    height: 799,
  }),
  planteInterieur: responsivePhoto({
    nom: 'produit-plante-interieur',
    largeurs: [360, 554],
    alt: 'Dracaena vert en pot pour décorer un intérieur',
    width: 554,
    height: 554,
  }),
  palmierCuillere: responsivePhoto({
    nom: 'produit-palmier-cuillere',
    largeurs: [480, 720],
    alt: 'Palmier cuillère en pot',
    width: 720,
    height: 953,
  }),
  bambou: responsivePhoto({
    nom: 'produit-bambou',
    largeurs: [480, 720],
    alt: 'Bambou décoratif en pot',
    width: 720,
    height: 980,
  }),
  bouquetRosesNaturelles: responsivePhoto({
    nom: 'produit-bouquet-roses-naturelles',
    largeurs: [480, 720],
    alt: 'Bouquet de roses naturelles',
    width: 720,
    height: 800,
  }),
  chrysanthemeBlanc: responsivePhoto({
    nom: 'produit-chrysantheme-blanc',
    largeurs: [480, 800],
    alt: 'Chrysanthème blanc',
    width: 800,
    height: 800,
  }),
  chrysanthemeBicolore: responsivePhoto({
    nom: 'produit-chrysantheme-bicolore',
    largeurs: [480, 600],
    alt: 'Chrysanthème bicolore',
    width: 600,
    height: 600,
  }),
  chrysanthemeViolet: responsivePhoto({
    nom: 'produit-chrysantheme-violet',
    largeurs: [360, 460],
    alt: 'Chrysanthème violet',
    width: 460,
    height: 460,
  }),
  hortensiaBlanc: responsivePhoto({
    nom: 'produit-hortensia-blanc',
    largeurs: [360, 447],
    alt: 'Hortensia blanc',
    width: 447,
    height: 447,
  }),
  hortensiaFuchsia: responsivePhoto({
    nom: 'produit-hortensia-fuchsia',
    largeurs: [480, 960],
    alt: 'Hortensia fuchsia',
    width: 1536,
    height: 2048,
  }),
  hortensiaVert: responsivePhoto({
    nom: 'produit-hortensia-vert',
    largeurs: [480, 1000],
    alt: 'Hortensia vert',
    width: 1000,
    height: 1000,
  }),
  lysOrientalBlanc: responsivePhoto({
    nom: 'produit-lys-oriental-blanc',
    largeurs: [320, 388],
    alt: 'Lys oriental blanc',
    width: 388,
    height: 515,
  }),
  lysOrientalRose: responsivePhoto({
    nom: 'produit-lys-oriental-rose',
    largeurs: [360, 447],
    alt: 'Lys oriental rose',
    width: 447,
    height: 447,
  }),
  lysAsiatiqueBlanc: responsivePhoto({
    nom: 'produit-lys-asiatique-blanc',
    largeurs: [480, 554],
    alt: 'Lys asiatique blanc',
    width: 554,
    height: 554,
  }),
  lysAsiatiqueOrange: responsivePhoto({
    nom: 'produit-lys-asiatique-orange',
    largeurs: [480, 554],
    alt: 'Lys asiatique orange',
    width: 554,
    height: 554,
  }),
  lysAsiatiqueRouge: responsivePhoto({
    nom: 'produit-lys-asiatique-rouge',
    largeurs: [360, 450],
    alt: 'Lys asiatique rouge',
    width: 450,
    height: 600,
  }),
  roseBlanche: responsivePhoto({
    nom: 'produit-rose-blanche',
    largeurs: [480, 678],
    alt: 'Rose blanche',
    width: 678,
    height: 452,
  }),
  roseJaune: responsivePhoto({
    nom: 'produit-rose-jaune',
    largeurs: [480, 600],
    alt: 'Rose jaune',
    width: 600,
    height: 600,
  }),
  roseOrange: responsivePhoto({
    nom: 'produit-rose-orange',
    largeurs: [480, 591],
    alt: 'Rose orange',
    width: 591,
    height: 519,
  }),
  roseRouge: responsivePhoto({
    nom: 'produit-rose-rouge',
    largeurs: [480, 554],
    alt: 'Rose rouge',
    width: 554,
    height: 554,
  }),
  roseRose: responsivePhoto({
    nom: 'produit-rose-rose',
    largeurs: [480, 960],
    alt: 'Rose rose',
    width: 1160,
    height: 670,
  }),
  spraysBlanc: responsivePhoto({
    nom: 'produit-sprays-blanc',
    largeurs: [360, 400],
    alt: 'Sprays blancs',
    width: 400,
    height: 533,
  }),
  spraysOrange: responsivePhoto({
    nom: 'produit-sprays-orange',
    largeurs: [320, 387],
    alt: 'Sprays orange',
    width: 387,
    height: 516,
  }),
  spraysRouge: responsivePhoto({
    nom: 'produit-sprays-rouge',
    largeurs: [320, 387],
    alt: 'Sprays rouges',
    width: 387,
    height: 516,
  }),
  cachePotVide: responsivePhoto({
    nom: 'produit-cache-pot-vide',
    largeurs: [480, 720],
    alt: 'Cache-pot vide décoratif',
    width: 720,
    height: 960,
  }),
  cachePotGrisOndule: responsivePhoto({
    nom: 'produit-cache-pot-gris-ondule',
    largeurs: [480, 960],
    alt: 'Cache-pot gris à relief ondulé',
    width: 960,
    height: 1280,
  }),
  cachePotGrisArrondi: responsivePhoto({
    nom: 'produit-cache-pot-gris-arrondi',
    largeurs: [480, 960],
    alt: 'Cache-pot gris texturé à la forme arrondie',
    width: 1148,
    height: 1280,
  }),
  cachePotBlancMouchete: responsivePhoto({
    nom: 'produit-cache-pot-blanc-mouchete',
    largeurs: [480, 960],
    alt: 'Cache-pot blanc moucheté de noir',
    width: 1008,
    height: 1280,
  }),
  cachePotBeigeArrondi: responsivePhoto({
    nom: 'produit-cache-pot-beige-arrondi',
    largeurs: [480, 810],
    alt: 'Cache-pot beige texturé à la forme arrondie',
    width: 810,
    height: 1080,
  }),
  cachePotBlancHaut: responsivePhoto({
    nom: 'produit-cache-pot-blanc-haut',
    largeurs: [480, 960],
    alt: 'Cache-pot blanc haut à relief vertical',
    width: 1024,
    height: 1280,
  }),
  cachePotNoirHaut: responsivePhoto({
    nom: 'produit-cache-pot-noir-haut',
    largeurs: [480, 848],
    alt: 'Cache-pot noir haut à relief vertical',
    width: 848,
    height: 1280,
  }),
  cachePotVertHaut: responsivePhoto({
    nom: 'produit-cache-pot-vert-haut',
    largeurs: [480, 716],
    alt: 'Cache-pot vert haut de forme carrée',
    width: 716,
    height: 1280,
  }),
  cachePotBleuHaut: responsivePhoto({
    nom: 'produit-cache-pot-bleu-haut',
    largeurs: [480, 844],
    alt: 'Cache-pot bleu haut de forme carrée',
    width: 844,
    height: 1280,
  }),
  vasesDecoratifs100: responsivePhoto({
    nom: 'produit-petits-vases-decoratifs',
    largeurs: [360, 608],
    alt: 'Trois petits vases décoratifs transparents, bruns et roses',
    width: 608,
    height: 1080,
  }),
  vasesSablier: responsivePhoto({
    nom: 'produit-vases-sablier-colores',
    largeurs: [360, 608],
    alt: 'Vases sablier en verre bleu et vert',
    width: 608,
    height: 1080,
  }),
  vasesBouteilleColores: responsivePhoto({
    nom: 'produit-vases-bouteille-colores',
    largeurs: [360, 608],
    alt: 'Vases bouteille en verre vert et orangé',
    width: 608,
    height: 1080,
  }),
  vasesGrisTorsades: responsivePhoto({
    nom: 'produit-vases-gris-torsades',
    largeurs: [360, 608],
    alt: 'Deux vases élancés en verre gris torsadé',
    width: 608,
    height: 1080,
  }),
  vasesCylindriquesTransparents: responsivePhoto({
    nom: 'produit-vases-cylindriques-transparents',
    largeurs: [360, 556],
    alt: 'Sélection de vases cylindriques transparents',
    width: 556,
    height: 979,
  }),
  bouquetRosesAPartir: responsivePhoto({
    nom: 'produit-bouquet-roses-a-partir',
    largeurs: [480, 720],
    alt: 'Bouquet de roses naturelles',
    width: 720,
    height: 960,
  }),
  langueDeBelleMere: responsivePhoto({
    nom: 'produit-langue-de-belle-mere',
    largeurs: [480, 714],
    alt: 'Langue de belle-mère en pot',
    width: 714,
    height: 1280,
  }),
  panierRamadan: responsivePhoto({
    nom: 'produit-panier-ramadan',
    largeurs: [480, 720],
    alt: 'Panier Ramadan garni',
    width: 720,
    height: 782,
  }),
  gerbeFunebreArtificielle: responsivePhoto({
    nom: 'produit-gerbe-funebre-artificielle',
    largeurs: [480, 810],
    alt: 'Gerbe funèbre artificielle',
    width: 810,
    height: 1080,
  }),
  jatropha: responsivePhoto({
    nom: 'produit-jatropha',
    largeurs: [480, 836],
    alt: 'Jatropha en pot',
    width: 836,
    height: 1280,
  }),
  pachiraArbreArgent: responsivePhoto({
    nom: 'produit-pachira-arbre-argent',
    largeurs: [480, 810],
    alt: 'Pachira, arbre à argent en pot',
    width: 810,
    height: 1080,
  }),
  terrarium: responsivePhoto({
    nom: 'produit-terrarium',
    largeurs: [480, 720],
    alt: 'Terrarium décoratif',
    width: 720,
    height: 1280,
  }),
  dieffenbachia: responsivePhoto({
    nom: 'produit-dieffenbachia',
    largeurs: [480, 1080],
    alt: 'Dieffenbachia en pot',
    width: 1080,
    height: 970,
  }),
  bouquetRosesColorees: responsivePhoto({
    nom: 'produit-bouquet-roses-colorees',
    largeurs: [480, 830],
    alt: 'Bouquet de roses colorées',
    width: 830,
    height: 1080,
  }),
  bouquetSeoul: responsivePhoto({
    nom: 'produit-bouquet-seoul',
    largeurs: [480, 984],
    alt: 'Bouquet Séoul avec roses jaunes et rouges',
    width: 984,
    height: 1280,
  }),
  langueDeBelleMereCachePot: responsivePhoto({
    nom: 'produit-langue-de-belle-mere-cache-pot',
    largeurs: [360, 464],
    alt: 'Langue de belle-mère avec cache-pot blanc',
    width: 464,
    height: 1080,
  }),
  aglaonema: responsivePhoto({
    nom: 'produit-aglaonema',
    largeurs: [480, 960],
    alt: 'Aglaonema en pot',
    width: 960,
    height: 1280,
  }),
  bouquetDauphineMissGuinee: responsivePhoto({
    nom: 'produit-bouquet-dauphine-miss-guinee',
    largeurs: [480, 810],
    alt: 'Bouquet Dauphine Miss Guinée',
    width: 810,
    height: 1080,
  }),
  planteCrayonEuphorbia: responsivePhoto({
    nom: 'produit-plante-crayon-euphorbia-tirucalli',
    largeurs: [480, 960],
    alt: 'Plante crayon Euphorbia tirucalli en pot',
    width: 960,
    height: 1079,
  }),
  bouquetMariee: responsivePhoto({
    nom: 'produit-bouquet-mariee',
    largeurs: [480, 720],
    alt: 'Bouquet de mariée rose et blanc',
    width: 720,
    height: 1080,
  }),
  decorationBouteilleEvenementielle: responsivePhoto({
    nom: 'produit-decoration-bouteille-evenementielle',
    largeurs: [360, 498],
    alt: 'Décoration de bouteille événementielle avec fleurs et roses',
    width: 498,
    height: 1080,
  }),
  bouquetAccueil: responsivePhoto({
    nom: 'produit-bouquet-accueil',
    largeurs: [480, 960],
    alt: 'Bouquet d’accueil aux roses colorées',
    width: 960,
    height: 720,
  }),
  bouquetDeFleursColorees: responsivePhoto({
    nom: 'produit-bouquet-de-fleurs-colorees',
    largeurs: [480, 810],
    alt: 'Bouquet de fleurs colorées aux tons rose, jaune et orange',
    width: 810,
    height: 1080,
  }),
  bouquetDeFleursJauneBlanc: responsivePhoto({
    nom: 'produit-bouquet-de-fleurs-jaune-blanc',
    largeurs: [480, 810],
    alt: 'Bouquet de fleurs jaune et blanc',
    width: 810,
    height: 1080,
  }),
  bouquetRomantique: responsivePhoto({
    nom: 'produit-bouquet-romantique',
    largeurs: [480, 960],
    alt: 'Bouquet romantique rouge présenté en chambre',
    width: 960,
    height: 639,
  }),
  bouquetArgent: responsivePhoto({
    nom: 'produit-bouquet-argent',
    largeurs: [480, 810],
    alt: 'Bouquet d’argent avec roses rouges',
    width: 810,
    height: 1080,
  }),
  bouquetDeFleursAvecPeluche: responsivePhoto({
    nom: 'produit-bouquet-de-fleurs-avec-peluche',
    largeurs: [480, 794],
    alt: 'Bouquet de fleurs avec petite peluche',
    width: 794,
    height: 1080,
  }),
  bouquetDeMarieeArtificiel: responsivePhoto({
    nom: 'produit-bouquet-de-mariee-artificiel',
    largeurs: [480, 810],
    alt: 'Bouquet de mariée artificiel blanc',
    width: 810,
    height: 1080,
  }),
  pelucheLama: responsivePhoto({
    nom: 'produit-peluche-lama',
    largeurs: [480, 606],
    alt: 'Peluche lama blanche et bleue au pelage bouclé, nouée d’un ruban pastel',
    width: 606,
    height: 917,
  }),
  luminairePlafonnierAnneauxLed: responsivePhoto({
    nom: 'produit-luminaire-plafonnier-anneaux-led',
    largeurs: [480, 842],
    alt: 'Plafonnier LED moderne composé de cinq anneaux noirs et blancs',
    width: 842,
    height: 1000,
  }),
  luminaireSuspensionVerreAmbre: responsivePhoto({
    nom: 'produit-luminaire-suspension-verre-ambre',
    largeurs: [480, 681],
    alt: 'Composition de suspensions décoratives en verre transparent et ambré',
    width: 681,
    height: 451,
  }),
  luminaireSuspensionTripleVerre: responsivePhoto({
    nom: 'produit-luminaire-suspension-triple-verre',
    largeurs: [360, 447],
    alt: 'Suspension triple noire avec abat-jours cylindriques en verre',
    width: 447,
    height: 447,
  }),
  luminaireLustreCinqBranches: responsivePhoto({
    nom: 'produit-luminaire-lustre-cinq-branches',
    largeurs: [480, 600],
    alt: 'Lustre noir classique à cinq branches et globes blancs',
    width: 600,
    height: 600,
  }),
  luminaireSuspensionIndustrielle: responsivePhoto({
    nom: 'produit-luminaire-suspension-industrielle',
    largeurs: [480, 543],
    alt: 'Suspension double noire de style industriel au-dessus d’une table',
    width: 543,
    height: 509,
  }),
  pelucheOursBlanc: responsivePhoto({
    nom: 'produit-peluche-ours-blanc',
    largeurs: [480, 608],
    alt: 'Ours en peluche blanc au ruban de satin rose',
    width: 608,
    height: 1080,
  }),
  pelucheOursBrun: responsivePhoto({
    nom: 'produit-peluche-ours-brun',
    largeurs: [480, 608],
    alt: 'Ours en peluche brun vêtu d’un pull rayé rouge et blanc',
    width: 608,
    height: 1080,
  }),
  pelucheOursRouge: responsivePhoto({
    nom: 'produit-peluche-ours-rouge',
    largeurs: [480, 608],
    alt: 'Grand ours en peluche rouge « Love Sweet » au nœud vichy',
    width: 608,
    height: 1080,
  }),
  pelucheOursCoeur: responsivePhoto({
    nom: 'produit-peluche-ours-coeur',
    largeurs: [480, 608],
    alt: 'Grand ours en peluche blanc tenant un cœur rouge « Love You »',
    width: 608,
    height: 1080,
  }),
  pelucheViolette: responsivePhoto({
    nom: 'produit-peluche-violette',
    largeurs: [480, 1080],
    alt: 'Grande peluche violette avec rose rouge',
    width: 1080,
    height: 1026,
  }),
  grandOursBeige: responsivePhoto({
    nom: 'produit-grand-ours-beige',
    largeurs: [480, 810],
    alt: 'Grand ours en peluche beige au nœud vichy',
    width: 810,
    height: 1080,
  }),
  grandOursBlanc: responsivePhoto({
    nom: 'produit-grand-ours-blanc',
    largeurs: [480, 810],
    alt: 'Grand ours en peluche blanc au nœud vichy',
    width: 810,
    height: 1080,
  }),
  grandOursRose: responsivePhoto({
    nom: 'produit-grand-ours-rose',
    largeurs: [480, 810],
    alt: 'Grand ours en peluche rose au cœur brodé « Love »',
    width: 810,
    height: 1080,
  }),
  grandOursMarron: responsivePhoto({
    nom: 'produit-grand-ours-marron',
    largeurs: [480, 810],
    alt: 'Grand ours en peluche marron au nœud vichy',
    width: 810,
    height: 1080,
  }),
  grandOursViolet: responsivePhoto({
    nom: 'produit-grand-ours-violet',
    largeurs: [480, 810],
    alt: 'Grand ours en peluche violet au nœud vichy',
    width: 810,
    height: 1080,
  }),
  tableauChevalGris: responsivePhoto({
    nom: 'produit-tableau-cheval-gris',
    largeurs: [480, 810],
    alt: 'Tableau d’un cheval gris à la crinière tressée, harnais noir et or',
    width: 810,
    height: 1080,
  }),
  tableauPivoinesRoses: responsivePhoto({
    nom: 'produit-tableau-pivoines-roses',
    largeurs: [480, 810],
    alt: 'Tableau peint de pivoines roses et blanches sur fond vert doux',
    width: 810,
    height: 1080,
  }),
  tableauFeuillesMonstera: responsivePhoto({
    nom: 'produit-tableau-feuilles-monstera',
    largeurs: [480, 810],
    alt: 'Tableau aquarelle de feuilles de monstera vertes sur fond blanc, cadre noir',
    width: 810,
    height: 1080,
  }),
  tableauHorlogeFemmeRouge: responsivePhoto({
    nom: 'produit-tableau-horloge-femme-rouge',
    largeurs: [480, 810],
    alt: 'Tableau-horloge doré représentant une femme au chapeau rouge',
    width: 810,
    height: 1080,
  }),
  tableauCerfDore: responsivePhoto({
    nom: 'produit-tableau-cerf-dore',
    largeurs: [480, 810],
    alt: 'Tableau cerf doré sur fond noir et or rehaussé de cristaux, cadre doré',
    width: 810,
    height: 1080,
  }),
  tableauElephantBleuOr: responsivePhoto({
    nom: 'produit-tableau-elephant-bleu-or',
    largeurs: [480, 810],
    alt: 'Tableau éléphant bleu et or incrusté de cristaux, cadre argenté',
    width: 810,
    height: 1080,
  }),
  tableauFemmeFleursBlanches: responsivePhoto({
    nom: 'produit-tableau-femme-fleurs-blanches',
    largeurs: [480, 810],
    alt: 'Tableau d’une femme coiffée de fleurs blanches, feuillages dorés',
    width: 810,
    height: 1080,
  }),
  tableauFemmeRobeOrange: responsivePhoto({
    nom: 'produit-tableau-femme-robe-orange',
    largeurs: [480, 810],
    alt: 'Tableau d’une femme en robe orange à large chapeau, néon doré',
    width: 810,
    height: 1080,
  }),
  inspirationFlorale: responsivePhoto({
    nom: 'inspiration-florale',
    largeurs: [480, 810],
    alt: 'Inspiration florale Lizzirene Déco',
    width: 810,
    height: 1080,
  }),
}

export const SERVICE_THEME_PHOTOS = {
  decoration: responsivePhoto({
    nom: 'service-decoration-espaces',
    largeurs: [480, 800, 1280],
    alt: 'Intérieur décoré avec une composition florale et une ambiance élégante',
    width: 1280,
    height: 853,
    sizes:
      '(max-width: 720px) calc(100vw - 40px), (max-width: 1100px) 50vw, 25vw',
  }),
  creations: responsivePhoto({
    nom: 'service-creations-florales',
    largeurs: [480, 800, 1280],
    alt: 'Création florale artisanale composée pour offrir',
    width: 1280,
    height: 919,
    sizes:
      '(max-width: 720px) calc(100vw - 40px), (max-width: 1100px) 50vw, 25vw',
  }),
  evenements: responsivePhoto({
    nom: 'service-celebrations',
    largeurs: [480, 800, 1280],
    alt: 'Décoration florale d’événement avec table festive',
    width: 1280,
    height: 853,
    sizes:
      '(max-width: 720px) calc(100vw - 40px), (max-width: 1100px) 50vw, 25vw',
  }),
  hommages: responsivePhoto({
    nom: 'service-attentions-hommages',
    largeurs: [480, 800, 1280],
    alt: 'Composition sobre pour un hommage floral',
    width: 1280,
    height: 720,
    sizes:
      '(max-width: 720px) calc(100vw - 40px), (max-width: 1100px) 50vw, 25vw',
  }),
  hommageCondoleances: responsivePhoto({
    nom: 'service-hommage-condoleances',
    largeurs: [480, 800, 1280],
    alt: 'Composition florale de deuil pour hommages et condoléances',
    width: 1280,
    height: 720,
    sizes:
      '(max-width: 720px) calc(100vw - 40px), (max-width: 1100px) 50vw, 25vw',
  }),
  convalescence: responsivePhoto({
    nom: 'service-convalescence',
    largeurs: [480, 800, 1280],
    alt: 'Bouquet de convalescence pour souhaiter un prompt rétablissement',
    width: 1280,
    height: 720,
    sizes:
      '(max-width: 720px) calc(100vw - 40px), (max-width: 1100px) 50vw, 25vw',
  }),
  naissance: responsivePhoto({
    nom: 'service-visite-naissance',
    largeurs: [480, 800, 1280],
    alt: 'Bouquet et douceurs pour féliciter de jeunes parents après une naissance',
    width: 1280,
    height: 720,
    sizes:
      '(max-width: 720px) calc(100vw - 40px), (max-width: 1100px) 50vw, 25vw',
  }),
  anniversaire: responsivePhoto({
    nom: 'service-anniversaire',
    largeurs: [480, 800, 1280],
    alt: "Mise en scène florale pour célébrer un anniversaire",
    width: 1280,
    height: 720,
    sizes:
      '(max-width: 720px) calc(100vw - 40px), (max-width: 1100px) 50vw, 25vw',
  }),
  remiseDiplome: responsivePhoto({
    nom: 'service-remise-diplome',
    largeurs: [480, 800, 1280],
    alt: 'Bouquet de félicitations pour une remise de diplôme',
    width: 1280,
    height: 720,
    sizes:
      '(max-width: 720px) calc(100vw - 40px), (max-width: 1100px) 50vw, 25vw',
  }),
}

// Photos de la section Événements de l'accueil : une par carte, jamais
// réutilisée ailleurs. Les cartes recadrent en 16/10, d'où des rapports
// d'origine différents sans conséquence.
const PHOTO_EVENEMENT = ({ nom, largeurs, alt, width, height }) =>
  responsivePhoto({
    nom,
    largeurs,
    alt,
    width,
    height,
    sizes:
      '(max-width: 720px) calc(100vw - 40px), (max-width: 980px) 50vw, 33vw',
  })

export const PHOTOS_EVENEMENTS = {
  mariages: PHOTO_EVENEMENT({
    nom: 'prestation-mariage',
    largeurs: [480, 800, 1280],
    alt: 'Salle de réception de mariage dressée, tables fleuries et compositions pastel',
    width: 1280,
    height: 844,
  }),
  anniversaires: PHOTO_EVENEMENT({
    nom: 'prestation-anniversaire',
    largeurs: [480, 810],
    alt: "Bouquet d'anniversaire Lizzirene Déco : roses rouges, gypsophile, chocolats et coffret cadeau",
    width: 810,
    height: 1080,
  }),
  entreprises: PHOTO_EVENEMENT({
    nom: 'prestation-conseil-amenagement',
    largeurs: [480, 800, 1280],
    alt: 'Bureau aménagé avec des compositions florales blanches et des plantes vertes',
    width: 1280,
    height: 720,
  }),
}

export const HERO_IMAGES = [
  {
    src: asset('optimized/hero-nouveau-1672.webp'),
    mobileSrc: asset('optimized/hero-nouveau-mobile.webp'),
    label: 'Nouvelle ambiance florale Lizzirène Déco',
    position: 'center center',
  },
  {
    src: asset('optimized/hero-image1-1920.webp'),
    mobileSrc: asset('optimized/hero-image1-mobile.webp'),
    label: 'Compositions florales colorées',
    position: 'center center',
  },
  {
    src: asset('optimized/hero-image2-1080.webp'),
    mobileSrc: asset('optimized/hero-image2-mobile.webp'),
    label: 'Sélection de fleurs et cadeaux',
    position: 'center center',
  },
]

// Communes et quartiers de Conakry proposés à la livraison.
export const ZONES = ['Kaloum', 'Dixinn', 'Matam', 'Ratoma', 'Matoto', 'Autre']

export const waLink = (message) =>
  `https://wa.me/${CONTACT.whatsapp}?text=${encodeURIComponent(message)}`

// 350000 → "350 000 GNF"
export const formatPrice = (value) =>
  `${String(value).replace(/\B(?=(\d{3})+(?!\d))/g, ' ')} GNF`
